const songs = [
  {
    id: 1,
    url: require('../assets/audio/01_Ruhui_Rahayu.mp3'),
    title: 'Ruhui Rahayu',
    artist: 'Fataya Putri Cinta Ariyanto Abdur dan Miranty Karima',
    created: 'Muhammad Marwan, S.Pd',
    artwork: require('../assets/lirik/1_Ruhui_Rahayu.png'),
    duration: 367.8,
  },
  {
    id: 2,
    url: require('../assets/audio/02_Awal_Bamula.mp3'),
    title: 'Awal Bamula',
    artist: 'Fataya Putri Cinta Ariyanto Abdur dan Miranty Karima',
    created: 'Muhammad Marwan, S.Pd',
    artwork: require('../assets/lirik/2_Awal_Bamula.png'),
    duration: 310.8,
  },
  {
    id: 3,
    url: require('../assets/audio/03_Bahibur_Diri.mp3'),
    title: 'Bahibur Diri',
    artist: 'Fataya Putri Cinta Ariyanto Abdur dan Miranty Karima',
    created: 'Muhammad Marwan, S.Pd',
    artwork: require('../assets/lirik/3_Bahibur_Diri.png'),
    duration: 246,
  },
  {
    id: 4,
    url: require('../assets/audio/04_Baturai_Nyanyi.mp3'),
    title: 'Baturai Nyanyi',
    artist: 'Fataya Putri Cinta Ariyanto Abdur dan Miranty Karima',
    created: 'Muhammad Marwan, S.Pd',
    artwork: require('../assets/lirik/4_Baturai_Nyanyi.png'),
    duration: 327.6,
  },
  {
    id: 5,
    url: require('../assets/audio/05_Barasa_rasa.mp3'),
    title: 'Barasa Rasa',
    artist: 'Fataya Putri Cinta Ariyanto Abdur dan Miranty Karima',
    created: 'Muhammad Marwan, S.Pd',
    artwork: require('../assets/lirik/5_Barasa_Rasa.png'),
    duration: 273.6,
  },
  {
    id: 6,
    url: require('../assets/audio/06_Ditiwas_Jadi.mp3'),
    title: 'Ditiwas Jadi',
    artist: 'Fataya Putri Cinta Ariyanto Abdur dan Miranty Karima',
    created: 'Muhammad Marwan, S.Pd',
    artwork: require('../assets/lirik/6_Ditiwas_Jadi.png'),
    duration: 275.4,
  },
  {
    id: 7,
    url: require('../assets/audio/07_Sudah_JanjiNya.mp3'),
    title: 'Sudah JanjiNya',
    artist: 'Fataya Putri Cinta Ariyanto Abdur dan Miranty Karima',
    created: 'Muhammad Marwan, S.Pd',
    artwork: require('../assets/lirik/7_Sudah_Janjinya.png'),
    duration: 369.6,
  },
];

export default songs;
